name: 🚧 Test Build Changed Packages

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: Install Lerna and Dependencies
        run: |
          npm install --global lerna
          yarn install

      - name: Find modified packages
        id: lerna_changed
        run: |
          npx lerna changed --loglevel=silent --json > changed.json
          if [ -s changed.json ]; then
            jq -r '.[].name' changed.json > modified-packages.txt
          else
            echo "No modified packages" > modified-packages.txt

      - name: Display modified packages
        run: |
          cat modified-packages.txt

      - name: Build modified packages
        if: success()
        run: |
          if [ -s modified-packages.txt ]; then
            for package in $(cat modified-packages.txt); do
              echo "Building package: $package"
              npx lerna run build --scope $package
            done
          else
            echo "No modified packages to build."
          fi

      - name: Validate modified packages
        if: success()
        run: |
          if [ -s modified-packages.txt ]; then
            for package in $(cat modified-packages.txt); do
              echo "Validating package: $package"
              npx lerna run validate --scope $package
            done
          else
            echo "No modified packages to validate."
          fi
